# General
default-language: en-GB

# MongoDB
mongodb-cluster-address:

mongodb-username:
mongodb-password:

# Discord
discord-server-invite-code:

survival-world-names:
  - world
  - world_nether
  - world_the_end
